services:
  bot:
    build: ./bot
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file:
      - stack.env
    volumes:
      - ./data:/app/data
    environment:
      - FETCH_SCRIPT=/app/scripts/new_script.py
      - DATA_DIR=/app/data
